'use client';
import { use, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { api } from '@/app/lib/api';
import { getStoredToken } from '@/app/lib/auth';

type Product = { id:string; name:string; itemCode:string; status:string; description?:string; baseUnit?:string; defaultCaseSize?:number; category?:{name:string}; brand?:{name:string}; manufacturer?:{name:string}; barcodes?:{id:string;code:string;identifierType:string;packagingLevel:string;isPrimary:boolean}[]; translations?:{id:string;locale:string;name:string}[]; suppliers?:{id:string;supplier?:{name:string};supplierProductCode?:string;currentUnitCost?:number}[] };
export default function ProductDetailPage({params}:{params:Promise<{id:string}>}) {
 const {id}=use(params);const router=useRouter();
 const [product,setProduct]=useState<Product|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [tab,setTab]=useState('Overview');const [barcode,setBarcode]=useState('');const [saving,setSaving]=useState(false);const [refresh,setRefresh]=useState(0);
 useEffect(()=>{const token=getStoredToken();if(!token){router.replace('/');return;}let active=true;api.get<Product>('/api/v1/products/'+encodeURIComponent(id),token).then(p=>{if(active)setProduct(p);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[id,router,refresh]);
 async function addBarcode(e:React.FormEvent){e.preventDefault();const token=getStoredToken();if(!token)return;setSaving(true);try{await api.post('/api/v1/products/'+encodeURIComponent(id)+'/barcodes',{code:barcode.trim(),identifierType:barcode.length===13?'EAN_13':'CODE_128',packagingLevel:'CONSUMER_UNIT',isPrimary:!product?.barcodes?.length},token);setBarcode('');setRefresh(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Failed to add barcode');}finally{setSaving(false);}}
 const tabs=['Overview','Barcodes','Translations','Suppliers'];
 return <div className="catalog-page"><div className="catalog-heading"><div><Link href="/products" className="catalog-view">← Products</Link><h1>{product?.name||'Product details'}</h1><p>{product?.itemCode||'Product catalogue'}</p></div>{product&&<span className="catalog-status">{product.status}</span>}</div>{loading?<div className="audit-empty">Loading product…</div>:error&&!product?<div className="audit-empty audit-error">{error}</div>:product&&<section className="audit-panel"><div className="product-tabs">{tabs.map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>{error&&<p role="alert" className="product-alert">{error}</p>}<div className="product-tab-body">{tab==='Overview'&&<div className="product-details-grid">{[['Item code',product.itemCode],['Name',product.name],['Category',product.category?.name],['Brand',product.brand?.name],['Manufacturer',product.manufacturer?.name],['Base unit',product.baseUnit],['Case size',product.defaultCaseSize],['Description',product.description]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value||'—'}</strong></div>)}</div>}{tab==='Barcodes'&&<><h2>Barcodes & identifiers</h2><form className="product-barcode-form" onSubmit={addBarcode}><input className="form-input" placeholder="Scan or enter barcode" aria-label="Barcode" value={barcode} onChange={e=>setBarcode(e.target.value)}/><button className="btn btn-primary" disabled={saving||!barcode.trim()}>Add barcode</button></form><div className="audit-table-wrap"><table className="audit-table"><thead><tr><th>Code</th><th>Type</th><th>Packaging</th><th>Primary</th></tr></thead><tbody>{product.barcodes?.map(b=><tr key={b.id}><td>{b.code}</td><td>{b.identifierType}</td><td>{b.packagingLevel}</td><td>{b.isPrimary?'Yes':'No'}</td></tr>)}</tbody></table></div></>}{tab==='Translations'&&<><h2>Translations</h2><div className="audit-table-wrap"><table className="audit-table"><thead><tr><th>Language</th><th>Name</th></tr></thead><tbody>{product.translations?.map(t=><tr key={t.id}><td>{t.locale}</td><td>{t.name}</td></tr>)}</tbody></table></div></>}{tab==='Suppliers'&&<><h2>Suppliers</h2><div className="audit-table-wrap"><table className="audit-table"><thead><tr><th>Supplier</th><th>Code</th><th>Unit cost</th></tr></thead><tbody>{product.suppliers?.map(s=><tr key={s.id}><td>{s.supplier?.name||'—'}</td><td>{s.supplierProductCode||'—'}</td><td>{s.currentUnitCost??'—'}</td></tr>)}</tbody></table></div></>}</div></section>}</div>;
}
