"use client";
import {createContext,useContext,useEffect,useMemo,useState,ReactNode} from "react";
import {useRouter} from "next/navigation";
import {IconButton,Menu,MenuItem,Tooltip} from "@mui/material";
import CloseOutlined from "@mui/icons-material/CloseOutlined";
import KeyboardArrowDownOutlined from "@mui/icons-material/KeyboardArrowDownOutlined";
import RestoreOutlined from "@mui/icons-material/RestoreOutlined";
export type WorkspaceTab={id:string;title:string;href:string;pinned?:boolean;dirty?:boolean;state?:Record<string,unknown>};
type Ctx={tabs:WorkspaceTab[];activeId:string;open:(t:WorkspaceTab,newTab?:boolean)=>void;activate:(t:WorkspaceTab)=>void;openRoute:(href:string,title:string,newTab?:boolean)=>void;close:(id:string)=>void;closeOthers:(id:string)=>void;closeRight:(id:string)=>void;closeAllProducts:()=>void;togglePin:(id:string)=>void;duplicate:(id:string)=>void;copyLink:(id:string)=>void;saveState:(id:string,state:Record<string,unknown>)=>void;getState:(id:string)=>Record<string,unknown>|undefined;recent:WorkspaceTab[];reopenLast:()=>void};
const WorkspaceContext=createContext<Ctx|null>(null);
const home:WorkspaceTab={id:"dashboard",title:"Dashboard",href:"/",pinned:true};
const productsRoot:WorkspaceTab={id:"products",title:"Products",href:"/products",pinned:true};
export function WorkspaceProvider({children}:{children:ReactNode}){
 const router=useRouter();const[tabs,setTabs]=useState<WorkspaceTab[]>([productsRoot]);const[activeId,setActiveId]=useState("products");const[recent,setRecent]=useState<WorkspaceTab[]>([]);
 useEffect(()=>{try{const path=window.location.pathname;const isProducts=path.startsWith("/products");const x=localStorage.getItem("omnicore-tabs");let saved:WorkspaceTab[]=[];if(x){const s=JSON.parse(x);if(Array.isArray(s))saved=s}const normalized=saved.filter((t:WorkspaceTab)=>t.id!=="products"&&t.id!=="dashboard"&&!t.id.startsWith("dashboard-"));if(isProducts){setTabs([productsRoot,...normalized]);const code=new URLSearchParams(window.location.search).get("item");setActiveId(code?"product-"+code:"products")}else if(path==="/"){setTabs([home,...normalized]);setActiveId("dashboard")}else{setTabs(saved.length?saved:[home]);const a=localStorage.getItem("omnicore-active-tab");if(a)setActiveId(a)}const r=localStorage.getItem("omnicore-recent-tabs");if(r)setRecent(JSON.parse(r))}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("omnicore-tabs",JSON.stringify(tabs));localStorage.setItem("omnicore-active-tab",activeId);localStorage.setItem("omnicore-recent-tabs",JSON.stringify(recent.slice(0,10)))}catch{}},[tabs,activeId,recent]);
 const navigate=(t:WorkspaceTab)=>{setActiveId(t.id);router.push(t.href);window.dispatchEvent(new CustomEvent("omnicore-workspace-navigate",{detail:{href:t.href,id:t.id,state:t.state||{}}}))};
 const open=(t:WorkspaceTab,newTab=false)=>{let target=t;setTabs(v=>{const found=v.find(x=>x.id===t.id);if(found){target=found;return v}if(newTab)return[...v,t];const i=v.findIndex(x=>x.id===activeId);if(i<0||v[i]?.pinned)return[...v,t];const n=[...v];setRecent(r=>[v[i],...r].slice(0,10));n[i]=t;return n});setTimeout(()=>navigate(target),0)};
 const activate=(t:WorkspaceTab)=>navigate(t);
 const openRoute=(href:string,title:string,newTab=true)=>open({id:"route-"+href.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase(),title,href},newTab);
 const close=(id:string)=>setTabs(v=>{const i=v.findIndex(x=>x.id===id);if(i<0||v[i].pinned)return v;const closing=v[i],n=v.filter(x=>x.id!==id),safe=n.length?n:[home];setRecent(r=>[closing,...r.filter(x=>x.id!==closing.id)].slice(0,10));if(id===activeId){const next=safe[Math.max(0,Math.min(i-1,safe.length-1))];setTimeout(()=>navigate(next),0)}return safe});
 const closeOthers=(id:string)=>setTabs(v=>v.filter(x=>x.id===id||x.pinned));
 const closeRight=(id:string)=>setTabs(v=>{const i=v.findIndex(x=>x.id===id);if(i<0)return v;const removed=v.slice(i+1).filter(x=>!x.pinned);if(removed.length)setRecent(r=>[...removed.reverse(),...r].filter((t,j,a)=>a.findIndex(x=>x.id===t.id)===j).slice(0,10));return v.filter((x,j)=>j<=i||x.pinned)});
 const closeAllProducts=()=>setTabs(v=>{const keep=v.filter(x=>x.id==="products"||x.pinned&&!x.id.startsWith("product-"));const removed=v.filter(x=>!keep.some(k=>k.id===x.id));if(removed.length)setRecent(r=>[...removed.reverse(),...r].filter((t,j,a)=>a.findIndex(x=>x.id===t.id)===j).slice(0,10));const safe=keep.length?keep:[productsRoot];if(!safe.some(x=>x.id===activeId)){const next=safe[0];setTimeout(()=>navigate(next),0)}return safe});
 const togglePin=(id:string)=>{if(id==="products"||id==="dashboard")return;setTabs(v=>v.map(x=>x.id===id?{...x,pinned:!x.pinned}:x))};
 const duplicate=(id:string)=>{const t=tabs.find(x=>x.id===id);if(t)open({...t,id:t.id+"-copy-"+Date.now(),title:t.title+" · Copy",pinned:false},true)};
 const copyLink=async(id:string)=>{const t=tabs.find(x=>x.id===id);if(!t)return;try{await navigator.clipboard.writeText(new URL(t.href,window.location.origin).toString())}catch{}};
 const saveState=(id:string,state:Record<string,unknown>)=>setTabs(v=>v.map(x=>x.id===id?{...x,state:{...(x.state||{}),...state}}:x));
 const getState=(id:string)=>tabs.find(x=>x.id===id)?.state;
 const reopenLast=()=>{const t=recent[0];if(t){setRecent(r=>r.slice(1));open({...t,pinned:false},true)}};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!e.ctrlKey)return;if(e.key==="w"){e.preventDefault();close(activeId)}if(e.key==="Tab"){e.preventDefault();const i=tabs.findIndex(x=>x.id===activeId),d=e.shiftKey?-1:1;activate(tabs[(i+d+tabs.length)%tabs.length])}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[tabs,activeId]);
 return <WorkspaceContext.Provider value={{tabs,activeId,open,activate,openRoute,close,closeOthers,closeRight,closeAllProducts,togglePin,duplicate,copyLink,saveState,getState,recent,reopenLast}}>{children}</WorkspaceContext.Provider>
}
export function useWorkspace(){return useContext(WorkspaceContext)!}
export function WorkspaceTabs(){
 const w=useWorkspace();const[menu,setMenu]=useState<string|null>(null);const[allOpen,setAllOpen]=useState(false);const[anchorEl,setAnchorEl]=useState<HTMLElement|null>(null);
 const visible=useMemo(()=>w.tabs.slice(0,7),[w.tabs]);
 return <div className="workspaceTabs">{visible.map(t=><div key={t.id} className={"workspaceTab "+(t.id===w.activeId?"active ":"")+(t.pinned?"pinned":"")} onClick={()=>w.activate(t)} onContextMenu={e=>{e.preventDefault();e.stopPropagation();setAnchorEl(e.currentTarget);setMenu(t.id)}} title={t.title}>{t.pinned&&<span className="pinMark">●</span>}<span>{t.dirty?"● ":""}{t.title}</span>{!t.pinned&&w.tabs.length>1&&<Tooltip title="Close tab"><IconButton size="small" aria-label="Close tab" onClick={e=>{e.stopPropagation();w.close(t.id)}}><CloseOutlined fontSize="inherit"/></IconButton></Tooltip>}{menu===t.id&&<Menu open anchorEl={anchorEl} onClose={()=>{setMenu(null);setAnchorEl(null)}} anchorOrigin={{vertical:"bottom",horizontal:"left"}} transformOrigin={{vertical:"top",horizontal:"left"}} slotProps={{paper:{sx:{zIndex:20000,minWidth:210}}}}><MenuItem onClick={()=>{w.close(t.id);setMenu(null);setAnchorEl(null)}} disabled={t.pinned}>Close</MenuItem><MenuItem onClick={()=>{w.closeOthers(t.id);setMenu(null);setAnchorEl(null)}}>Close other tabs</MenuItem><MenuItem onClick={()=>{w.closeRight(t.id);setMenu(null);setAnchorEl(null)}}>Close tabs to the right</MenuItem><MenuItem onClick={()=>{w.closeAllProducts();setMenu(null);setAnchorEl(null)}}>Close all product tabs</MenuItem><MenuItem onClick={()=>{w.duplicate(t.id);setMenu(null);setAnchorEl(null)}}>Duplicate tab</MenuItem><MenuItem onClick={()=>{w.copyLink(t.id);setMenu(null);setAnchorEl(null)}}>Copy product link</MenuItem></Menu>}</div>)}{w.tabs.length>7&&<div className="tabOverflow"><button onClick={()=>setAllOpen(!allOpen)}><KeyboardArrowDownOutlined fontSize="inherit"/> {w.tabs.length-7}</button>{allOpen&&<div className="allTabs">{w.tabs.slice(7).map(t=><button key={t.id} onClick={()=>{w.activate(t);setAllOpen(false)}}>{t.title}</button>)}</div>}</div>}{w.recent.length>0&&<Tooltip title="Reopen recently closed tab"><IconButton className="reopenTab" size="small" onClick={w.reopenLast}><RestoreOutlined fontSize="small"/></IconButton></Tooltip>}</div>
}

export function WorkspaceLink({href,title,children,className}:{href:string;title:string;children:ReactNode;className?:string}){const w=useWorkspace();return <a href={href} className={className} onClick={e=>{e.preventDefault();w.openRoute(href,title,true)}} onDoubleClick={e=>{e.preventDefault();w.openRoute(href,title,true)}}>{children}</a>}
