'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
type Product={itemCode:string,name:string,alt:string,barcode:string,category:string,supplier:string,cost:number,retail:number,stock:number,status:'Active'|'Low stock'|'Out of stock'};
const products:Product[]=[
{itemCode:'15953',name:'MLEKPOL MASLO EXTRA 200G',alt:'Butter Extra 200g',barcode:'5900820007737',category:'Dairy',supplier:'Master Media',cost:1.42,retail:2.29,stock:3,status:'Low stock'},
{itemCode:'17041',name:'KABANOS KIELBASA DLA CHLOPA',alt:'Smoked kabanos sausage',barcode:'5902800246008',category:'Meat',supplier:'Wabar',cost:1.15,retail:2.19,stock:42,status:'Active'},
{itemCode:'21256',name:'TARCZYNSKI INDYK',alt:'Turkey sausage',barcode:'5908230521256',category:'Meat',supplier:'Wabar',cost:1.83,retail:3.49,stock:28,status:'Active'},
{itemCode:'15513',name:'DUDA SZYNKA NATURALNA',alt:'Natural ham',barcode:'5900854015513',category:'Deli',supplier:'Spizarnia',cost:3.82,retail:5.99,stock:16,status:'Active'},
{itemCode:'21072',name:'COCA-COLA ORIGINAL TASTE 330ML',alt:'Coca-Cola 330ml can',barcode:'5449000000996',category:'Beverages',supplier:'Master Media',cost:.62,retail:1.29,stock:0,status:'Out of stock'},
{itemCode:'18420',name:'TYMBARK JABLKO MIENTA 1L',alt:'Apple & mint drink',barcode:'5900334018420',category:'Beverages',supplier:'Bestway',cost:.88,retail:1.69,stock:64,status:'Active'},
{itemCode:'1354',name:'CARNATI PICANTI',alt:'Spicy sausages',barcode:'5900000013548',category:'Meat',supplier:'Marion Trading',cost:4.12,retail:6.49,stock:21,status:'Active'},
{itemCode:'1805',name:'CIOLAN AFUMAT',alt:'Smoked pork knuckle',barcode:'5900000018055',category:'Meat',supplier:'Marion Trading',cost:3.76,retail:5.99,stock:9,status:'Active'}];
export default function Products(){const[q,setQ]=useState('');const[status,setStatus]=useState('All');const[selected,setSelected]=useState<Product|null>(null);const filtered=useMemo(()=>products.filter(p=>(status==='All'||p.status===status)&&((p.itemCode+' '+p.name+' '+p.alt+' '+p.barcode+' '+p.supplier).toLowerCase().includes(q.toLowerCase()))),[q,status]);return <div className="productApp">
<aside className="productSide"><Link href="/" className="pBrand"><span>OC</span><div><b>OmniCore</b><small>Retail Operating System</small></div></Link><Link href="/" className="pNav">⌂ Dashboard</Link><div className="pGroup">CORE RETAIL</div><div className="pNav active">▣ Products</div><div className="pNav">⌘ Categories</div><div className="pNav">£ Pricing</div><div className="pNav">▥ Barcodes & EANs</div><div className="pNav">◇ Product Passport</div><div className="pGroup">SUPPLY CHAIN</div><div className="pNav">⇄ Suppliers</div><div className="pNav">☷ Purchasing</div><div className="pNav">▤ Deliveries</div><div className="pGroup">INVENTORY</div><div className="pNav">▦ Stock & Inventory</div><div className="pNav">⌗ Stocktake (HHU)</div></aside>
<main className="productMain"><header className="pTop"><Link href="/" className="pMobileLogo">OC</Link><div className="pGlobal">⌕ Search OmniCore...</div><button>All Stores⌄</button><button>◉</button><div className="avatar">AD</div></header><div className="pContent">
<div className="pTitle"><div><div className="crumb">Core Retail / Products</div><h1>Products</h1><p>Central product catalogue across every store, supplier and channel.</p></div><div className="pActions"><button>⇧ Import</button><button>⇩ Export</button><button className="primary">＋ Add Product</button></div></div>
<section className="pStats"><div><span>Total Products</span><b>12,486</b><small>↑ 124 this month</small></div><div><span>Active</span><b>11,942</b><small>95.6% of catalogue</small></div><div><span>Low Stock</span><b>47</b><small className="warn">Needs attention</small></div><div><span>Missing Barcode</span><b>23</b><small>Review records</small></div><div><span>Duplicates</span><b>8</b><small className="bad">Resolve matches</small></div></section>
<section className="catalog"><div className="catalogHead"><div className="productSearch">⌕ <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search item code, product, EAN, supplier..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Active</option><option>Low stock</option><option>Out of stock</option></select><button>Category⌄</button><button>Supplier⌄</button><button>More filters</button><button className="scanBtn">⌗ Scan</button></div>
<div className="tableWrap"><table className="productTable"><thead><tr><th>PRODUCT</th><th>ITEM CODE</th><th>BARCODE / EAN</th><th>CATEGORY</th><th>PRIMARY SUPPLIER</th><th>COST</th><th>RETAIL</th><th>MARGIN</th><th>STOCK</th><th>STATUS</th><th></th></tr></thead><tbody>{filtered.map(p=>{const margin=Math.round((p.retail-p.cost)/p.retail*100);return <tr key={p.itemCode} onClick={()=>setSelected(p)}><td><div className="prodCell"><span className="prodImg">▣</span><div><b>{p.name}</b><small>{p.alt}</small></div></div></td><td><b>{p.itemCode}</b></td><td className="mono">{p.barcode}</td><td>{p.category}</td><td>{p.supplier}</td><td>£{p.cost.toFixed(2)}</td><td><b>£{p.retail.toFixed(2)}</b></td><td className="good">{margin}%</td><td><b>{p.stock}</b></td><td><span className={'status '+p.status.toLowerCase().replaceAll(' ','-')}>{p.status}</span></td><td>›</td></tr>})}</tbody></table></div><div className="catalogFoot"><span>Showing {filtered.length} of 12,486 products</span><div><button>‹</button><button className="page">1</button><button>2</button><button>3</button><button>…</button><button>125</button><button>›</button></div></div></section>
</div></main>
<nav className="productBottom"><Link href="/">⌂<span>Home</span></Link><button className="selected">▣<span>Products</span></button><button className="centerScan">⌗<span>Scan</span></button><button>▦<span>Stock</span></button><button>•••<span>More</span></button></nav>
{selected&&<div className="detailBackdrop" onClick={()=>setSelected(null)}><aside className="detailPanel" onClick={e=>e.stopPropagation()}><button className="closeDetail" onClick={()=>setSelected(null)}>×</button><div className="detailHero"><span className="bigProd">▣</span><div><span className={'status '+selected.status.toLowerCase().replaceAll(' ','-')}>{selected.status}</span><h2>{selected.name}</h2><p>{selected.alt}</p><b>Item {selected.itemCode}</b></div></div><div className="tabs"><b>Overview</b><span>Barcodes</span><span>Pricing</span><span>Suppliers</span><span>Stock</span><span>Sales</span><span>Activity</span></div><div className="detailGrid"><div><label>Primary barcode</label><b>{selected.barcode}</b></div><div><label>Category</label><b>{selected.category}</b></div><div><label>Primary supplier</label><b>{selected.supplier}</b></div><div><label>Cost</label><b>£{selected.cost.toFixed(2)}</b></div><div><label>Retail price</label><b>£{selected.retail.toFixed(2)}</b></div><div><label>Total stock</label><b>{selected.stock} units</b></div></div><h3>Stock by store</h3>{['Hounslow','Hayes','Perivale','Watford','Gravesend','Eastham','Streatham'].map((s,i)=><div className="storeStock" key={s}><span>{s}</span><b>{Math.max(0,selected.stock-i*3)}</b></div>)}<button className="primary full">Edit product</button></aside></div>}
</div>}