'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
type Product={itemCode:string,name:string,alt:string,barcode:string,category:string,supplier:string,cost:number,retail:number,stock:number,status:'Active'|'Low stock'|'Out of stock'};
const products:Product[]=[
{itemCode:'15953',name:'MLEKPOL MASLO EXTRA 200G',alt:'Butter Extra 200g',barcode:'5900820007737',category:'Dairy',supplier:'Master Media',cost:1.42,retail:2.29,stock:3,status:'Low stock'},
{itemCode:'17041',name:'KABANOS KIELBASA DLA CHLOPA',alt:'Smoked kabanos sausage',barcode:'5902800246008',category:'Meat',supplier:'Wabar',cost:1.15,retail:2.19,stock:42,status:'Active'},
{itemCode:'21256',name:'TARCZYNSKI INDYK',alt:'Turkey sausage',barcode:'5908230521256',category:'Meat',supplier:'Wabar',cost:1.83,retail:3.49,stock:28,status:'Active'},
{itemCode:'15513',name:'DUDA SZYNKA NATURALNA',alt:'Natural ham',barcode:'5900854015513',category:'Deli',supplier:'Spizarnia',cost:3.82,retail:5.99,stock:16,status:'Active'},
{itemCode:'21072',name:'COCA-COLA ORIGINAL TASTE 330ML',alt:'Coca-Cola 330ml can',barcode:'5449000000996',category:'Beverages',supplier:'Master Media',cost:.62,retail:1.29,stock:0,status:'Out of stock'},
{itemCode:'18420',name:'TYMBARK JABLKO MIENTA 1L',alt:'Apple & mint drink',barcode:'5900334018420',category:'Beverages',supplier:'Bestway',cost:.88,retail:1.69,stock:64,status:'Active'},
{itemCode:'1354',name:'CARNATI PICANTI',alt:'Spicy sausages',barcode:'5900000013548',category:'Meat',supplier:'Marion Trading',cost:4.12,retail:6.49,stock:21,status:'Active'},
{itemCode:'1805',name:'CIOLAN AFUMAT',alt:'Smoked pork knuckle',barcode:'5900000018055',category:'Meat',supplier:'Marion Trading',cost:3.76,retail:5.99,stock:9,status:'Active'}];
export default function Products(){const[menuOpen,setMenuOpen]=useState(false);const[globalSearchOpen,setGlobalSearchOpen]=useState(false);const globalSearchRef=useRef<HTMLDivElement>(null);const globalInputRef=useRef<HTMLInputElement>(null);useEffect(()=>{if(globalSearchOpen)globalInputRef.current?.focus()},[globalSearchOpen]);useEffect(()=>{const close=(e:PointerEvent)=>{if(globalSearchOpen&&globalSearchRef.current&&!globalSearchRef.current.contains(e.target as Node))setGlobalSearchOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[globalSearchOpen]);const[q,setQ]=useState('');const[status,setStatus]=useState('All');const[selected,setSelected]=useState<Product|null>(null);const[detailTab,setDetailTab]=useState('Overview');const[eventType,setEventType]=useState('All');const filtered=useMemo(()=>products.filter(p=>(status==='All'||p.status===status)&&((p.itemCode+' '+p.name+' '+p.alt+' '+p.barcode+' '+p.supplier).toLowerCase().includes(q.toLowerCase()))),[q,status]);return <div className="productApp"><div className={menuOpen?"drawerBackdrop open":"drawerBackdrop"} onClick={()=>setMenuOpen(false)}/>
<aside className={menuOpen?"productSide open":"productSide"}><button className="drawerClose" onClick={()=>setMenuOpen(false)}>×</button><Link href="/" className="pBrand"><span className="logoMark"><img src="/EE8811F8-FC53-4FA4-81E3-3E5B28F44B0F.png" alt="OmniCore"/></span><div><b>OmniCore</b><small>Retail Operating System</small></div></Link><Link href="/" className="pNav">⌂ Dashboard</Link><div className="pGroup">CORE RETAIL</div><div className="pNav active">▣ Products</div><div className="pNav">⌘ Categories</div><div className="pNav">£ Pricing</div><div className="pNav">▥ Barcodes & EANs</div><div className="pNav">◇ Product Passport</div><div className="pGroup">SUPPLY CHAIN</div><div className="pNav">⇄ Suppliers</div><div className="pNav">☷ Purchasing</div><div className="pNav">▤ Deliveries</div><div className="pGroup">INVENTORY</div><div className="pNav">▦ Stock & Inventory</div><div className="pNav">⌗ Stocktake (HHU)</div></aside>
<main className="productMain"><header className="pTop"><button className="productMenuButton" onClick={()=>setMenuOpen(true)}>☰</button><Link href="/" className="pMobileLogo logoMark"><img src="/EE8811F8-FC53-4FA4-81E3-3E5B28F44B0F.png" alt="OmniCore"/></Link><div ref={globalSearchRef} className={globalSearchOpen?"pGlobal globalOpen":"pGlobal"}><button className="pSearchTrigger" onClick={()=>setGlobalSearchOpen(true)}>⌕</button>{globalSearchOpen&&<input ref={globalInputRef} className="pGlobalInput" placeholder="Search OmniCore..." />}</div><button>All Stores⌄</button><button>◉</button><div className="avatar">AD</div></header><div className="pContent">
<div className="pTitle"><div><div className="crumb">Core Retail / Products</div><h1>Products</h1><p>Search, govern and resolve exceptions across the global product catalogue.</p></div><div className="pActions"><button>⇧ Import</button><button>⇩ Export</button><button className="primary">＋ Add Product</button></div></div>
<section className="pStats"><div><span>Total Products</span><b>1,284,692</b><small>↑ 124 this month</small></div><div><span>Active</span><b>1,241,903</b><small>95.6% of catalogue</small></div><div><span>Needs Attention</span><b>8,421</b><small className="warn">Needs attention</small></div><div><span>Missing EAN</span><b>4,921</b><small>Review records</small></div><div><span>Possible Duplicates</span><b>2,184</b><small className="bad">Resolve matches</small></div></section>
<section className="catalog"><div className="catalogHead"><div className="productSearch">⌕ <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search 1,284,692 products · item code, EAN, supplier code, name..."/></div><div className="quickViews"><button>All Products</button><button>Issues 8,421</button><button>Duplicates 2,184</button><button>Missing Data 4,921</button></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Active</option><option>Low stock</option><option>Out of stock</option></select><button>Category⌄</button><button>Supplier⌄</button><button>More filters</button><button className="scanBtn">⌗ Scan</button></div>
<div className="tableWrap"><table className="productTable"><thead><tr><th>PRODUCT</th><th>ITEM CODE</th><th>BARCODE / EAN</th><th>CATEGORY</th><th>PRIMARY SUPPLIER</th><th>COST</th><th>RETAIL</th><th>MARGIN</th><th>STOCK</th><th>STATUS</th><th></th></tr></thead><tbody>{filtered.map(p=>{const margin=Math.round((p.retail-p.cost)/p.retail*100);return <tr key={p.itemCode} onClick={()=>{setSelected(p);setDetailTab('Overview')}}><td><div className="prodCell"><span className="prodImg">▣</span><div><b>{p.name}</b><small>{p.alt}</small></div></div></td><td><b>{p.itemCode}</b></td><td className="mono">{p.barcode}</td><td>{p.category}</td><td>{p.supplier}</td><td>£{p.cost.toFixed(2)}</td><td><b>£{p.retail.toFixed(2)}</b></td><td className="good">{margin}%</td><td><b>{p.stock}</b></td><td><span className={'status '+p.status.toLowerCase().replaceAll(' ','-')}>{p.status}</span></td><td>›</td></tr>})}</tbody></table></div><div className="catalogFoot"><span>Showing {filtered.length} sample records · 1,284,692 indexed products</span><div><button>‹</button><button className="page">1</button><button>2</button><button>3</button><button>…</button><button>125</button><button>›</button></div></div></section>
</div></main>
<nav className="productBottom"><Link href="/">⌂<span>Home</span></Link><button className="selected">▣<span>Products</span></button><button className="centerScan">⌗<span>Scan</span></button><button>▦<span>Stock</span></button><button onClick={()=>setMenuOpen(true)}>•••<span>More</span></button></nav>
{selected&&<div className="detailBackdrop" onClick={()=>setSelected(null)}><aside className="detailPanel" onClick={e=>e.stopPropagation()}><button className="closeDetail" onClick={()=>setSelected(null)}>×</button><div className="detailHero"><span className="bigProd">▣</span><div><span className={'status '+selected.status.toLowerCase().replaceAll(' ','-')}>{selected.status}</span><h2>{selected.name}</h2><p>{selected.alt}</p><b>Item {selected.itemCode}</b></div></div><div className="coreIdentity"><div><label>PRODUCT CODE · REQUIRED</label><strong>{selected.itemCode}</strong><small>Permanent OmniCore identity · unique across tenant</small></div><span className="identityOk">✓ Core identity</span></div>
<div className="tabs productTabs">{['Overview','Barcodes & Packs','Pricing','Suppliers','Inventory','Sales','History'].map(t=><button key={t} className={detailTab===t?'tabActive':''} onClick={()=>setDetailTab(t)}>{t}</button>)}</div>
{detailTab==='History'&&<section className="historyWorkspace"><div className="historyHeader"><div><h3>Product activity timeline</h3><p>Reconstruct exactly what happened to this product for any period, store and event type.</p></div></div><div className="historyFilters"><button>Today</button><button>7 days</button><button className="selectedRange">30 days</button><button>Custom range</button><select><option>All stores</option><option>Hounslow</option><option>Hayes</option><option>Perivale</option></select><select value={eventType} onChange={e=>setEventType(e.target.value)}><option>All</option><option>Sale</option><option>Delivery</option><option>Wastage</option><option>Stock Adjustment</option><option>Price Change</option></select><button>Export</button></div><div className="historySummary"><div><span>Opening stock</span><b>128</b></div><div><span>Delivered</span><b className="good">+48</b></div><div><span>Sold</span><b>-91</b></div><div><span>Wastage</span><b className="bad">-3</b></div><div><span>Adjustments</span><b>-2</b></div><div><span>Closing stock</span><b>80</b></div></div><div className="eventList">{[
['06 Oct 2026 · 14:42','Sale','Hounslow','POS 03 · Receipt #84921','82','80','-2','System / Till 03'],
['06 Oct 2026 · 12:18','Stock Adjustment','Hounslow','Cycle count correction · Reason: count variance','79','82','+3','S. Manager'],
['06 Oct 2026 · 09:06','Delivery','Hounslow','GRN #GR-108842 · PO #PO-40192 · Wabar','67','79','+12','A. Perera'],
['05 Oct 2026 · 18:31','Wastage','Hounslow','Damaged / unsellable · Ref WST-22018','69','67','-2','M. Silva'],
['05 Oct 2026 · 15:04','Sale','Hounslow','POS 01 · Receipt #84177','70','69','-1','System / Till 01'],
['05 Oct 2026 · 08:52','Price Change','All stores','Retail £2.09 → £2.19 · Promotion ended','70','70','0','Admin']
].filter(e=>eventType==='All'||e[1]===eventType).map((e,i)=><div className="eventRow" key={i}><div className={'eventDot event'+e[1].replaceAll(' ','')}></div><div className="eventMain"><div className="eventTop"><b>{e[1]}</b><span>{e[0]}</span></div><p>{e[3]}</p><small>{e[2]} · by {e[7]}</small></div><div className="stockDelta"><span>Before <b>{e[4]}</b></span><strong>→</strong><span>After <b>{e[5]}</b></span><em>{e[6]}</em></div></div>)}</div></section>}
{detailTab!=='History'&&<><section className="detailSection"><div className="sectionTitle"><div><h3>Product identity</h3><p>One product code controls every barcode, pack configuration and commercial record.</p></div><button>Edit identity</button></div><div className="detailGrid identityGrid"><div><label>Product code</label><b>{selected.itemCode}</b></div><div><label>Product name</label><b>{selected.name}</b></div><div><label>English name</label><b>{selected.alt}</b></div><div><label>Category</label><b>{selected.category}</b></div></div></section>
<section className="detailSection"><div className="sectionTitle"><div><h3>Barcodes & pack hierarchy</h3><p>Multiple identifiers can belong to this product. Each barcode defines its own pack level and quantity.</p></div><button>＋ Add barcode</button></div>
<div className="barcodeCards"><div className="barcodeCard primaryBarcode"><div className="barcodeHead"><span>RETAIL / EACH</span><i>Primary</i></div><b className="barcodeNumber">{selected.barcode}</b><div className="packMeta"><span><small>Pack level</small><b>Consumer Unit</b></span><span><small>Units</small><b>1 each</b></span><span><small>Retail</small><b>£{selected.retail.toFixed(2)}</b></span></div></div><div className="barcodeCard"><div className="barcodeHead"><span>OUTER / CASE</span><i>Case</i></div><b className="barcodeNumber">{selected.barcode.slice(0,-1)}14</b><div className="packMeta"><span><small>Pack level</small><b>Case</b></span><span><small>Case size</small><b>12 × each</b></span><span><small>Case cost</small><b>£{(selected.cost*12).toFixed(2)}</b></span></div></div><button className="addPack">＋ Add case / outer / inner barcode</button></div></section>
<section className="detailSection"><div className="sectionTitle"><div><h3>Commercial</h3><p>Current buying and selling values. Store-level overrides can be managed in Pricing.</p></div><button>Pricing history</button></div><div className="commercialGrid"><div><label>Unit cost</label><b>£{selected.cost.toFixed(2)}</b></div><div><label>Retail price</label><b>£{selected.retail.toFixed(2)}</b></div><div><label>Margin</label><b className="good">{Math.round((selected.retail-selected.cost)/selected.retail*100)}%</b></div><div><label>VAT</label><b>20%</b></div><div><label>Primary supplier</label><b>{selected.supplier}</b></div><div><label>Status</label><span className={'status '+selected.status.toLowerCase().replaceAll(' ','-')}>{selected.status}</span></div></div></section>
<section className="detailSection"><div className="sectionTitle"><div><h3>Inventory by store</h3><p>Live stock position across the organisation.</p></div><b>{selected.stock} total units</b></div>{['Hounslow','Hayes','Perivale','Watford','Gravesend','Eastham','Streatham'].map((s,i)=><div className="storeStock" key={s}><span>{s}</span><b>{Math.max(0,selected.stock-i*3)}</b></div>)}</section><button className="primary full">Edit product master</button></>}</aside></div>}
</div>}