'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {AppSidebar,DrawerBackdrop} from '../app-shell';
import {useWorkspace,WorkspaceTabs} from '../workspace';
type Promo={id:string;name:string;scope:string;type:string;status:string;startsAt:string;endsAt:string;products?:unknown[];stores?:unknown[];zones?:unknown[]};
type Zone={id:string;name:string;code:string;assignments?:{store:{name:string}}[]};
export default function PromotionsPage(){
 const [menu,setMenu]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [data,setData]=useState<{promotions:Promo[];zones:Zone[]}>({promotions:[],zones:[]});
 const [tab,setTab]=useState<'promotions'|'zones'>('promotions');
 const [showCreate,setShowCreate]=useState(false);
 const [draft,setDraft]=useState({name:'',scope:'ALL_STORES',type:'PERCENT_OFF',startsAt:'',endsAt:'',productId:'',value:'',requiredQuantity:'',targets:''});
 const [saving,setSaving]=useState(false);
 async function saveDraft(e:FormEvent){e.preventDefault();setError('');setSaving(true);try{const res=await fetch('/api/head-office/promotions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const body=await res.json();if(!res.ok)throw new Error(body.error||'Unable to create promotion');setShowCreate(false);setLoading(true);const fresh=await fetch('/api/head-office/promotions',{cache:'no-store'});if(!fresh.ok)throw new Error('Unable to refresh promotions');setData(await fresh.json());}catch(e){setError(e instanceof Error?e.message:'Unable to save promotion')}finally{setSaving(false);setLoading(false)}}
 const {openRoute}=useWorkspace();
 useEffect(()=>{let active=true;fetch('/api/head-office/promotions',{cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||'Failed to load promotions');if(active)setData(body)}).catch(e=>{if(active)setError(String(e.message||e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 return <div className="app"><AppSidebar active="Promotions" open={menu} onClose={()=>setMenu(false)}/><DrawerBackdrop open={menu} onClose={()=>setMenu(false)}/><main className="main"><WorkspaceTabs/><div className="content">
 <div className="hero"><div><h1>Promotions & Pricing Zones</h1><p className="muted">Head Office · centrally managed promotions for every store</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="filter" onClick={()=>openRoute('/products','Products')}>View products</button><button className="filter" onClick={()=>setShowCreate(v=>!v)}>{showCreate?'Close draft':'New promotion'}</button></div></div>
 <div className="filters" style={{marginBottom:16}}><button className="filter" style={{fontWeight:tab==='promotions'?700:400}} onClick={()=>setTab('promotions')}>Promotions</button><button className="filter" style={{fontWeight:tab==='zones'?700:400}} onClick={()=>setTab('zones')}>Pricing zones</button></div>
 {showCreate&&<form onSubmit={saveDraft} className="card" style={{padding:20,marginBottom:16,display:'grid',gap:12}}><h3>Create Head Office promotion</h3><p className="muted">Draft only. Saving requires an authenticated Head Office session and will remain blocked until access is configured.</p><label>Promotion name<input className="input" required maxLength={120} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}><label>Store targeting<select className="input" value={draft.scope} onChange={e=>setDraft({...draft,scope:e.target.value})}><option value="ALL_STORES">All stores</option><option value="ZONES">Pricing zones</option><option value="STORES">Selected stores</option></select></label><label>Offer type<select className="input" value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option value="PERCENT_OFF">Percentage off</option><option value="AMOUNT_OFF">Amount off</option><option value="FIXED_PRICE">Fixed price</option><option value="MULTIBUY_FIXED_PRICE">Multibuy fixed price</option></select></label><label>Starts<input className="input" type="datetime-local" required value={draft.startsAt} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label>Ends<input className="input" type="datetime-local" required min={draft.startsAt} value={draft.endsAt} onChange={e=>setDraft({...draft,endsAt:e.target.value})}/></label><label>Product ID<input className="input" required value={draft.productId} onChange={e=>setDraft({...draft,productId:e.target.value})} placeholder="Product UUID"/></label><label>Offer value<input className="input" type="number" min="0" max={draft.type==='PERCENT_OFF'?'100':undefined} step="0.01" required value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label>{draft.type==='MULTIBUY_FIXED_PRICE'&&<label>Required units<input className="input" type="number" min="2" step="1" required value={draft.requiredQuantity} onChange={e=>setDraft({...draft,requiredQuantity:e.target.value})}/></label>}</div>{draft.scope!=='ALL_STORES'&&<label>{draft.scope==='STORES'?'Store IDs':'Zone IDs'} (comma separated)<input className="input" required value={draft.targets} onChange={e=>setDraft({...draft,targets:e.target.value})}/></label>}<button className="filter" disabled={saving||!!error}>{saving?'Saving…':'Save draft (Head Office only)'}</button></form>}
 <div className="card" style={{padding:20}}>
 {loading?<p>Loading Head Office promotions…</p>:error?<div role="alert"><h3>Access or configuration required</h3><p>{error}</p><p className="muted">Promotion management remains locked until employee authentication and Head Office permissions are connected. No sample promotions are shown as live data.</p></div>:tab==='promotions'?<>
 <h3>Promotions ({data.promotions.length})</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Name</th><th>Scope</th><th>Offer</th><th>Status</th><th>Start</th><th>End</th></tr></thead><tbody>{data.promotions.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.scope.replaceAll('_',' ')}</td><td>{p.type.replaceAll('_',' ')}</td><td>{p.status}</td><td>{new Date(p.startsAt).toLocaleDateString('en-GB')}</td><td>{new Date(p.endsAt).toLocaleDateString('en-GB')}</td></tr>)}</tbody></table></div>{!data.promotions.length&&<p className="muted">No promotions created yet.</p>}</>:<>
 <h3>Store pricing zones ({data.zones.length})</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{data.zones.map(z=><div key={z.id} className="card" style={{padding:16}}><strong>{z.name}</strong><p className="muted">{z.code}</p><p>{z.assignments?.map(a=>a.store.name).join(', ')||'No assigned stores'}</p></div>)}</div>{!data.zones.length&&<p className="muted">No zones configured yet.</p>}</>}
 </div></div></main></div>
}
